name: drop_down_data
description: Drop-down list of data.dart allowing to make one or more selections and to search among the data.dart or an identifier.
version: 1.0.3
# authors: AYLIcrea with AsYouLikeKit <aylibox@gmail.com>
homepage: https://github.com/MrPiou94/drop_down_data

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
